services:

  strapi:
    container_name: afz-strapi
    build:
      context: ./backend
      dockerfile: Dockerfile.strapi
    env_file:
      - .env
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    volumes:
      - ./backend:/srv/app
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

  nextjs:
    container_name: afz-nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

  postgres:
    container_name: afz-postgres
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
